<?php
 /*
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_SizeChart
 * @copyright   Copyright (c) 2016 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
*/
?>
<?php if ($this->isModuleEnable()) { ?>
<style>
.pschart-sizechart-link {
	border: 1px solid <?php echo $this->getBorderColor(); ?> ;
	background-color: <?php echo $this->getBackgroundColor(); ?> ;
	background-image: url(<?php echo $this->getIconButton(); ?>);
	color: <?php echo  $this->getTextColor(); ?>;
}

.pschart-sizechart-link:hover {
    color: <?php echo  $this->getTextColor(); ?>;
}
</style>
<?php } ?>