

<fieldset id="massstockupdate_mapping" class="fieldset admin__fieldset ">
    <legend class="admin__legend legend">
        <span><?php echo __('Mapping'); ?></span>
    </legend>
    <br>
    <div class="message message-error error" id="mapping-preview-error" style="display:none"></div>
    <div class="message message-warning warning" id="mapping-preview-warning" style="display:none"></div>
    <table id="mapping-preview" border='0' bgcolor="white" cellpadding="0" cellspacing="0" >
    </table>
    <script>
        var mappingRefreshUrl = '<?php echo $block->getUrl('*/mapping/refresh', array('id' => $block->getProfileId())); ?>';
    </script>
</fieldset>

<fieldset id="massstockupdate_default-values" class="fieldset admin__fieldset ">
    <legend class="admin__legend legend">
        <span><?php echo __('Additional column mapping'); ?></span>

    </legend>
    <div id='default-values'></div> 

</fieldset>
<script>


    var MassStockUpdate = {
        data: {
            images: {
                add: {
                    src: "<?php echo $block->getViewFileUrl("images/rule_component_add.gif") ?>"

                },
                remove: {
                    src: "<?php echo $block->getViewFileUrl("images/rule_component_remove.gif") ?>"

                }
            },
            translate: {
                add: "<?php echo __("Add a new column"); ?>",
                remove: "<?php echo __("Remove this column"); ?>",
                attribute: "<?php echo __("Attribute"); ?>",
                value: "<?php echo __("Default value"); ?>"

            },
            attributes:<?php echo $block->getAttributes() ?>
        }
    };







</script>
<?php echo $block->getFormHtml(); ?>